-- MySQL Script generated by MySQL Workbench
-- Thu Sep 26 11:30:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_internships2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `app_internships2` ;

-- -----------------------------------------------------
-- Schema app_internships2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_internships2` DEFAULT CHARACTER SET utf8 ;
USE `app_internships2` ;

-- -----------------------------------------------------
-- Table `app_internships2`.`contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`contracts` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`contracts` (
  `id` INT(11) NOT NULL COMMENT '		',
  `contractType` VARCHAR(45) NOT NULL,
  `contractText` VARCHAR(3700) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `contractType_UNIQUE` (`contractType` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `app_internships2`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`locations` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address1` VARCHAR(80) NULL,
  `address2` VARCHAR(80) NULL,
  `postalCode` INT NULL,
  `city` VARCHAR(45) NULL,
  `lat` DOUBLE NULL,
  `lng` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`companies` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`companies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `companyName` VARCHAR(80) NOT NULL,
  `location_id` INT NULL DEFAULT NULL,
  `website` VARCHAR(255) NULL,
  `contracts_id` INT(11) NOT NULL DEFAULT 3 COMMENT '3 = entreprise (i know….)',
  `englishSkills` TINYINT NOT NULL DEFAULT 0 COMMENT 'Tells if good english skills are required for the internship',
  `driverLicence` TINYINT NOT NULL DEFAULT 0 COMMENT 'Tells if the intern must have a driver license (for external missions)',
  `mptOk` TINYINT NOT NULL DEFAULT 1 COMMENT 'Tells if a MPT student who is only 4 days on site is acceptable for the job',
  PRIMARY KEY (`id`),
  INDEX `FKTypeContrat` (`contracts_id` ASC) VISIBLE,
  INDEX `FKLocation_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `FKTypeContrat`
    FOREIGN KEY (`contracts_id`)
    REFERENCES `app_internships2`.`contracts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKLocation`
    FOREIGN KEY (`location_id`)
    REFERENCES `app_internships2`.`locations` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`flocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`flocks` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`flocks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `flockName` VARCHAR(45) NOT NULL,
  `startYear` INT(11) NOT NULL,
  `classMaster_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fkmc_idx` (`classMaster_id` ASC) VISIBLE,
  CONSTRAINT `fkmc`
    FOREIGN KEY (`classMaster_id`)
    REFERENCES `app_internships2`.`persons` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`persons` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`persons` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `flock_id` INT(11) NULL DEFAULT NULL COMMENT 'flock = volée',
  `company_id` INT NULL DEFAULT NULL,
  `location_id` INT NULL DEFAULT NULL,
  `initials` VARCHAR(3) NULL,
  `upToDateDate` DATETIME NULL COMMENT 'Date/time at which the person has read all remarks',
  `intranetUserId` INT NULL DEFAULT '0' COMMENT 'IntranetUser ID',
  `obsolete` TINYINT NOT NULL DEFAULT 0,
  `mpt` INT NULL COMMENT 'For a student: is in MPT class',
  PRIMARY KEY (`id`),
  INDEX `FKVolee_idx` (`flock_id` ASC) VISIBLE,
  INDEX `FKEntreprise_idx` (`company_id` ASC) VISIBLE,
  INDEX `FKLocationPerson_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `FKEntreprise`
    FOREIGN KEY (`company_id`)
    REFERENCES `app_internships2`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FKVolee`
    FOREIGN KEY (`flock_id`)
    REFERENCES `app_internships2`.`flocks` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FKLocationPerson`
    FOREIGN KEY (`location_id`)
    REFERENCES `app_internships2`.`locations` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`contacttypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`contacttypes` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`contacttypes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contactTypeDescription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`contactinfos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`contactinfos` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`contactinfos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contacttypes_id` INT(11) NOT NULL DEFAULT '0',
  `persons_id` INT(11) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `rank` INT NOT NULL DEFAULT 99 COMMENT 'to order display',
  PRIMARY KEY (`id`),
  INDEX `FKType_idx` (`contacttypes_id` ASC) VISIBLE,
  INDEX `FKPers_idx` (`persons_id` ASC) VISIBLE,
  CONSTRAINT `FKPers`
    FOREIGN KEY (`persons_id`)
    REFERENCES `app_internships2`.`persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FKType`
    FOREIGN KEY (`contacttypes_id`)
    REFERENCES `app_internships2`.`contacttypes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 96
DEFAULT CHARACTER SET = utf8
COMMENT = 'contactinfos_id';


-- -----------------------------------------------------
-- Table `app_internships2`.`contractstates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`contractstates` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`contractstates` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `stateDescription` VARCHAR(45) NOT NULL,
  `details` TEXT NULL,
  `openForApplication` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`lifecycles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`lifecycles` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`lifecycles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `from_id` INT(11) NOT NULL,
  `to_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKFrom_idx` (`from_id` ASC) VISIBLE,
  INDEX `FKTo_idx` (`to_id` ASC) VISIBLE,
  CONSTRAINT `FKFrom`
    FOREIGN KEY (`from_id`)
    REFERENCES `app_internships2`.`contractstates` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FKTo`
    FOREIGN KEY (`to_id`)
    REFERENCES `app_internships2`.`contractstates` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`remarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`remarks` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`remarks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `remarkType` INT(11) NOT NULL COMMENT '1: Company\n2: Person\n3: -\n4: Visit\n5: Internship',
  `remarkOn_id` INT(11) NOT NULL,
  `remarkDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `author` VARCHAR(45) NOT NULL,
  `remarkText` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`internships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`internships` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`internships` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `companies_id` INT(11) NOT NULL,
  `beginDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `responsible_id` INT(11) NULL DEFAULT NULL COMMENT 'The day-to-day manager',
  `admin_id` INT(11) NULL DEFAULT NULL COMMENT 'The person who is responsible for the administrative matters',
  `intern_id` INT(11) NULL DEFAULT NULL COMMENT 'the student',
  `contractstate_id` INT(11) NULL DEFAULT 1,
  `previous_id` INT NULL COMMENT 'The internship before this one in this company',
  `internshipDescription` TEXT NULL DEFAULT NULL,
  `grossSalary` INT NULL DEFAULT 1230 COMMENT 'Dès 2017, tarifs « état de Vaud »:\n1er stage 1230.- , 2ème stage 1625.-',
  `contractGenerated` DATETIME NULL COMMENT 'Indicates that the contract has been generated and accepted by the user\n',
  PRIMARY KEY (`id`),
  INDEX `FKChez_idx` (`companies_id` ASC) VISIBLE,
  INDEX `FKResp_idx` (`responsible_id` ASC) VISIBLE,
  INDEX `FKRespAdmin_idx` (`admin_id` ASC) VISIBLE,
  INDEX `FKStatusContrat_idx` (`contractstate_id` ASC) VISIBLE,
  INDEX `FKStagiaire_idx` (`intern_id` ASC) VISIBLE,
  INDEX `FKPrecedent_idx` (`previous_id` ASC) VISIBLE,
  CONSTRAINT `FKChez`
    FOREIGN KEY (`companies_id`)
    REFERENCES `app_internships2`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FKResp`
    FOREIGN KEY (`responsible_id`)
    REFERENCES `app_internships2`.`persons` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FKRespAdmin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `app_internships2`.`persons` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FKStagiaire`
    FOREIGN KEY (`intern_id`)
    REFERENCES `app_internships2`.`persons` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FKStatusContrat`
    FOREIGN KEY (`contractstate_id`)
    REFERENCES `app_internships2`.`contractstates` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPrecedent`
    FOREIGN KEY (`previous_id`)
    REFERENCES `app_internships2`.`internships` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`activitytypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`activitytypes` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`activitytypes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `typeActivityDescription` VARCHAR(50) NULL,
  `RequireDetails` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`visitsstates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`visitsstates` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`visitsstates` (
  `id` INT NOT NULL,
  `stateName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`visits` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`visits` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `moment` DATETIME NULL,
  `confirmed` TINYINT(1) NOT NULL DEFAULT '0',
  `number` INT(11) NULL DEFAULT NULL COMMENT 'rank (first or second visit)',
  `internships_id` INT(11) NOT NULL,
  `grade` FLOAT NULL COMMENT 'Results of the evaluation',
  `visitsstates_id` INT NOT NULL,
  `mailstate` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKVisite_idx` (`internships_id` ASC) VISIBLE,
  INDEX `fk_visits_visitsstates1_idx` (`visitsstates_id` ASC) VISIBLE,
  CONSTRAINT `FKVisite`
    FOREIGN KEY (`internships_id`)
    REFERENCES `app_internships2`.`internships` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_visitsstates1`
    FOREIGN KEY (`visitsstates_id`)
    REFERENCES `app_internships2`.`visitsstates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`documents` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`documents` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `file` VARCHAR(255) NULL,
  `internships_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKStage_idx` (`internships_id` ASC) VISIBLE,
  CONSTRAINT `FKStage`
    FOREIGN KEY (`internships_id`)
    REFERENCES `app_internships2`.`internships` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`wishes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`wishes` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`wishes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `internships_id` INT NOT NULL,
  `persons_id` INT NOT NULL COMMENT 'The student who placed the wish',
  `rank` INT NOT NULL COMMENT 'Order of preference of the student',
  `workPlaceDistance` INT NULL COMMENT 'Distance in km between the workplace and the student’s home',
  `travelTime` INT NULL COMMENT 'Travel time using public transportation from person’s home to workplace, in minutes',
  `application` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `SouhaitePar_idx` (`persons_id` ASC) VISIBLE,
  INDEX `SouhaiteStage_idx` (`internships_id` ASC) VISIBLE,
  CONSTRAINT `SouhaitePar`
    FOREIGN KEY (`persons_id`)
    REFERENCES `app_internships2`.`persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `SouhaiteStage`
    FOREIGN KEY (`internships_id`)
    REFERENCES `app_internships2`.`internships` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`logbooks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`logbooks` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`logbooks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `internships_id` INT(11) NOT NULL,
  `entryDate` DATETIME NULL DEFAULT NULL,
  `duration` FLOAT(11) NULL DEFAULT NULL COMMENT 'Hours spent on the task',
  `activityDescription` VARCHAR(2000) NULL DEFAULT NULL,
  `activitytypes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_journal_stage1_idx` (`internships_id` ASC) VISIBLE,
  INDEX `fk_journal_typeactivite1_idx` (`activitytypes_id` ASC) VISIBLE,
  CONSTRAINT `fk_journal_stage1`
    FOREIGN KEY (`internships_id`)
    REFERENCES `app_internships2`.`internships` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_typeactivite1`
    FOREIGN KEY (`activitytypes_id`)
    REFERENCES `app_internships2`.`activitytypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `app_internships2`.`params`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`params` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`params` (
  `param_id` INT NOT NULL AUTO_INCREMENT,
  `paramName` VARCHAR(45) NOT NULL,
  `paramValueText` VARCHAR(255) NULL COMMENT 'Value if the parameter is of type text',
  `paramValueInt` INT NULL COMMENT 'Value if the parameter is of type int',
  `paramValueDate` DATETIME NULL COMMENT 'Value if the parameter is of type date',
  PRIMARY KEY (`param_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`evaluations` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`evaluations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `visit_id` INT NOT NULL,
  `editable` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fkvisit_idx` (`visit_id` ASC) VISIBLE,
  CONSTRAINT `fkvisit`
    FOREIGN KEY (`visit_id`)
    REFERENCES `app_internships2`.`visits` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`evaluationSections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`evaluationSections` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`evaluationSections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hasGrade` INT NOT NULL COMMENT 'Indicates wether this section is evaluated with a grade or is just gathering informations\n',
  `sectionName` VARCHAR(45) NOT NULL,
  `sectionType` INT NOT NULL DEFAULT 1 COMMENT '1 -> Formal evaluation\n2 -> List of tasks\n3 -> Feedback on training plan',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`criterias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`criterias` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`criterias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `criteriaName` VARCHAR(45) NOT NULL,
  `criteriaDetails` VARCHAR(1000) NULL,
  `maxPoints` INT NULL,
  `evaluationSection_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fksection_idx` (`evaluationSection_id` ASC) VISIBLE,
  CONSTRAINT `fksection`
    FOREIGN KEY (`evaluationSection_id`)
    REFERENCES `app_internships2`.`evaluationSections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_internships2`.`criteriaValues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_internships2`.`criteriaValues` ;

CREATE TABLE IF NOT EXISTS `app_internships2`.`criteriaValues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `evaluation_id` INT NOT NULL,
  `criteria_id` INT NOT NULL,
  `points` INT NOT NULL,
  `studentComments` VARCHAR(1000) NULL,
  `managerComments` VARCHAR(1000) NULL,
  `contextSpecifics` VARCHAR(1000) NULL COMMENT 'Allows to add details that are specific to this internship',
  PRIMARY KEY (`id`),
  INDEX `fkeval_idx` (`evaluation_id` ASC) VISIBLE,
  INDEX `fkcrit_idx` (`criteria_id` ASC) VISIBLE,
  CONSTRAINT `fkeval`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `app_internships2`.`evaluations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fkcrit`
    FOREIGN KEY (`criteria_id`)
    REFERENCES `app_internships2`.`criterias` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
